# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MY DOC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'GoogleAPIClientForREST/Drive', '~> 1.2.1'
    pod 'GoogleSignIn', '~> 4.1.1'
    pod 'SVProgressHUD', '~> 2.2'
    pod 'UtilityFramework'
  # Pods for MY DOC

  target 'MY DOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MY DOCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
